---
title: "Grade analysis"
format: html
---

```{r}
# | message: false
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stringr)
```


## Question 1
```{r message=FALSE}
grade <- vroom(here("grades.csv"))
```

## Question 2
```{r}
exam <-
  grade |>
  summarise(min(Exam, na.rm = TRUE),
            max(Exam, na.rm = TRUE),
            median(Exam, na.rm = TRUE),
            mean(Exam, na.rm = TRUE))
  
knitr::kable(exam)
```

## Question 3
```{r}
na_exam <- 
  grade |>
  filter(is.na(Exam)) |> nrow()
```


We observe that 60 students did not take the exam.


## Question 4
```{r}
grade |>
  ggplot(aes(x=Exam)) + geom_bar() +
  labs(title = "Distribution of grades at the exam")
```

## Question 5
```{r}
students_by_group <- 
  grade |>
  reframe(.by=Group, Id) |>
  group_by(Group)|>
  summarise(Count = n())

knitr::kable(students_by_group)
```

## Question 6
```{r}
students_by_group |>
ggplot(aes(x = Group, y = Count)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of students in each group")
```

## Question 7
```{r message=FALSE}
grade |>
  ggplot(aes(x=Exam)) + 
  geom_histogram(na.rm = TRUE) + 
  facet_wrap(~Group) +
  labs(title = "Distribution of grades at the exam by groups")
```


## Question 7(bis)
```{r}

```


## Question 8
```{r}
na_exam_by_groups <- 
  grade |>
  reframe(.by=Group, Id, Exam) |>
  group_by(Group) |>
  summarise(na_exam = sum(is.na(Exam)))
```

## Question 9
```{r}
na_exam_by_groups |>
  ggplot(aes(x=Group, y=na_exam)) + geom_col() +
  labs(title = "Distribution of missed exam by groups" , y = "Number of missed exam")
```

## Question 10
```{r}
grade_long_form <-
  grade |>
  pivot_longer(cols = -c(Id, Group))
```


## Question 11
```{r}
missed_exam_long_form <-
  grade_long_form |>
  group_by(Id) |>
  summarise(missed_exam = sum(is.na(value)))
```

## Question 12
```{r}
missed_exam_long_form |>
  ggplot(aes(x=missed_exam)) + geom_bar() +
  labs(title = "Distribution of missed exam per student")
```

## Question 13
```{r message=FALSE}
missed_exam_long_form_by_group <-
  grade_long_form |>
  group_by(Group, Id) %>%
  summarise(Missed_Exam = any(is.na(value))) %>%
  summarise(students_with_na_exam = sum(Missed_Exam))
```

## Question 14
```{r}
missed_online_exam_per_students <-
  grade_long_form |>
  filter(str_starts(name, "Online_MCQ_")) %>%
  group_by(Id) %>%
  summarise(missed_online_exam = sum(is.na(value)))
```

## Question 15
```{r}
graph <-
  grade |>
  left_join(missed_online_exam_per_students, by = "Id") 

ggplot(graph, aes(x=Exam)) + geom_bar() + facet_wrap(~missed_online_exam, scales = "free") +
  labs(title = "Distribution of the grades at the Exam conditioned by the number of missed online tests" , y = "count students")
```



